from typing import Any
from agent import Session, Response

def run(context: dict[str, Any], session: Session) -> Any: ...
def process_frontpage(data: Response, context: dict[str, Any], session: Session) -> Any: ...
def process_prodlist(data: Response, context: dict[str, Any], session: Session) -> Any: ...
def process_product(data: Response, context: dict[str, Any], session: Session) -> Any: ...
def process_reviews(data: Response, context: dict[str, Any], session: Session) -> Any: ...
