from typing import Any
from agent import Session


# Явно оголошуємо сигнатури ВСІХ функцій, які лінтер має бачити в clean файлі
def run(context: Any, session: Session) -> None: ...
def process_frontpage(data: Any, context: Any, session: Session) -> None: ...
def process_prodlist(data: Any, context: Any, session: Session) -> None: ...
def process_product(data: Any, context: Any, session: Session) -> None: ...
def process_reviews(data: Any, context: Any, session: Session) -> None: ...