"""add params

Revision ID: 54765cd1724b
Revises: 6123437bae71
Create Date: 2026-07-29 10:36:13.775005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54765cd1724b'
down_revision: Union[str, Sequence[str], None] = '6123437bae71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('description', sa.String(length=1000), nullable=True, default=None))
    op.add_column('agent', sa.Column('priority', sa.String(length=10), nullable=True, default=None))
    op.add_column('agent', sa.Column('group', sa.String(length=255), nullable=True, default=None))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'group')
    op.drop_column('agent', 'priority')
    op.drop_column('agent', 'description')
    # ### end Alembic commands ###
