"""del code, add max_emit

Revision ID: e64d9ec27516
Revises: 54765cd1724b
Create Date: 2026-08-04 11:04:48.503982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e64d9ec27516'
down_revision: Union[str, Sequence[str], None] = '54765cd1724b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('max_emit', sa.Integer(), nullable=True))
    op.drop_column('agent', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('code', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('agent', 'max_emit')
    # ### end Alembic commands ###
